name: Testing Dependancies
on: [push]
jobs:
  Run-All-Tests:
    name: "Run All Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
      
        run: npm install
        
      - name: Run tests
        run: npm run test
